Module7 task1
htmlacademy-nestjs/1806037-taskforce-2 pull request #11
Opened 2023-01-10 10:51 UTC by FirstBroRussia

2023-01-10 13:23 UTC, shad0w-jo4n requested changes

2023-01-10 13:23 UTC, shad0w-jo4n commented on taskforce/apps/notify/src/app/email-subscriber/email-subscriber.service.ts
> +    if (existSubscriber) { throw new CustomError('The subscriber with same email already exists', ExceptionEnum.Conflict) }
Соблюдай стиль кода, либо не ставь фигурные скобки, либо делай многострочный блок кода

2023-01-10 13:23 UTC, shad0w-jo4n commented on taskforce/apps/notify/src/app/email-subscriber/email-subscriber.service.ts
> +    const subscribersList = await this.notifyRepository.find();
лучше используй пагинацию, иначе так всю оперативку забьёшь, если там будут миллионы записей

2023-01-10 13:23 UTC, shad0w-jo4n commented on taskforce/apps/notify/src/app/mailer/mail.controller.ts
> +                  .catch(err => handleError(err));
почему не try-catch?

2023-01-10 13:23 UTC, shad0w-jo4n commented on taskforce/apps/task/src/app/task-category/task-category.controller.ts
> +              .catch(err => handleError(err))
почему не try-catch?

2023-01-10 14:19 UTC, FirstBroRussia commented on taskforce/apps/notify/src/app/email-subscriber/email-subscriber.service.ts
> +    if (existSubscriber) { throw new CustomError('The subscriber with same email already exists', ExceptionEnum.Conflict) }
+++

2023-01-11 11:58 UTC, shad0w-jo4n approved these changes

2023-01-11 11:58 UTC, merged